### ISSUE TITLE
not able to run the project

### ISSUE THREAD

**Issue by bishtvaishali** [tkim-snu/GLACNet#2]
I am trying to run the project with the pre-trained model. I followed all the steps mentioned in the Prerequisites and evaluation part. I downloaded the SIS file and the pre-trained models from the provided link and placed .pkl files in the models folder: encoder-0.pkl, decoder.pkl, vocab.pkl.

I am getting the below error message. I tried with both versions of Python 2.7 and 3.6

**ubuntu@ip-xxx-xx-xx-xxx:~/GLACNet****$ python3.6 eval.py --model_num 0**
Traceback (most recent call last):
  File "eval.py", line 81, in <module>
    vocab = pickle.load(f)
_pickle.UnpicklingError: invalid load key, '<'.

**My system configuration:**
GPU: 1 ,  vCPUs: 4
CUDA:  V10.0.130, Python: 3.6

Can you please help me if I am missing anything or doing something wrong..

Thank you

**Comment by tkim-snu** [comment]
The pretrained models can only work with python 3.6.
I've tested in the same environment as your system (cuda10, python3.6, pytorch1.2), but haven't found any problems.
(Note: don't run build_vocab.py to use pretrained models. It will overwrite the existing vocab.pkl file.)
Can you update the relevant libraries to the latest version and check the pickle library version?
I am using version 4.0 pickle library.

**Comment by tkim-snu** [comment]
The pretrained models can only work with python 3.6.
I've tested in the same environment as your system (cuda10, python3.6, pytorch1.2), but haven't found any problems.
(Note: don't run build_vocab.py to use pretrained models. It will overwrite the existing vocab.pkl file.)
Can you update the relevant libraries to the latest version and check the pickle library version?
What operating system are you using?
I am using version 4.0 pickle library and Ubuntu 18.04.
