### ISSUE TITLE
How to get a story for random images

### ISSUE THREAD

**Issue by KhushiGala** [tkim-snu/GLACNet#5]
How do I test your project on a set of random images using the pretrained models? Say, I have a folder that has 5 images and I need to generate text for them, is that possible?

**Comment by tkim-snu** [comment]
Of course. However, some code modification is required.
First, follow the instructions in the README.
After that you need to modify the inference.ipynb file so that it can read the images you want.
Please note that we plan to upload additional code for this in the near future.

**Comment by KhushiGala** [comment]
We tried changing the directory from which it is taking the images as the input but the story which it is generating is not at all relevant to the images
<img width="960" alt="2020-08-24" src="https://user-images.githubusercontent.com/48961185/91164866-66874480-e6ed-11ea-9929-a3a643cf9e56.png">

<img width="960" alt="2020-08-24 (5)" src="https://user-images.githubusercontent.com/48961185/91164915-7dc63200-e6ed-11ea-9b42-6d35171451cc.png">

**Comment by KhushiGala** [comment]
We have tried to run the inference.ipynb file using google colab. Here's a link to the notebook: https://colab.research.google.com/drive/1P9QICcVD15aTXgOQOsa1xktH2C_ddigq?usp=sharing

I have mounted my google drive to the notebook, and a folder named "sample_test" in the drive contains the images that I want to use for testing. Each time I run the code, the output text seems to change but the images remain blacked out. All the necessary files - encoder, decoder, vocab pickle files and the json files are present in the drive.

In the screenshot below you can see the paths set for image_dir and other variables:

<img width="960" alt="2020-08-25 (7)" src="https://user-images.githubusercontent.com/48961185/91212642-20060a00-e72e-11ea-94b2-881c8a957d88.png">

The Output:
<img width="960" alt="2020-08-25 (6)" src="https://user-images.githubusercontent.com/48961185/91212728-3f9d3280-e72e-11ea-8052-7899deb3b655.png">

The images in the sample_test folder are:

<img width="723" alt="2020-08-25 (3)" src="https://user-images.githubusercontent.com/48961185/91213060-afabb880-e72e-11ea-98bc-ebc7ee4525f6.png">

**Comment by tkim-snu** [comment]
I added the 'test.ipynb' file for your case.
But I couldn't test it because I don't have your photo files.
Try generating text using the 'test.ipynb' file.
Please refer to the changed code below.

image_files = ['929665.jpg', '929669.jpg', '929673.jpg', '929678.jpg', '929689.jpg']
for i in range(5):
    image = Image.open('sample_test/' + image_files[i]).convert('RGB')
    images.append(image)
    image = transform_image(image, transform)
    image_tensor.append(image)

**Comment by KhushiGala** [comment]
We implemented test.ipynb and we could generate stories from random images. Thank you so much for helping us out.

**Comment by KhushiGala** [comment]
Can you please share the number of epochs that you trained the model for, and what were the values of the other parameters to obtain the pretrained model that you have currently provided?
